CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectid INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make Web App', '1', 'Using Javascript', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make FeriApp', '1', 'Using Ionic', '2019-06-07');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Script', '1', 'Using Python', '2019-07-01');

-- Insert tasks data
INSERT INTO tasks(name, done, projectid)
    VALUES('Download Vuejs',false, 1);

INSERT INTO tasks(name, done, projectid)
    VALUES('Create UI WEB',false, 1);

INSERT INTO tasks(name, done, projectid)
    VALUES('Download Flutter',false, 2);

INSERT INTO tasks(name, done, projectid)
    VALUES('Design UI',false, 2);